Profile view
sh-internship/inventory-app-react pull request #36
Opened 2018-08-01 14:59 UTC by MaksZys

2018-08-01 19:54 UTC, MaksZys commented
## Tasks included in this pull request
- [x] #10 
- [x] #22 
- [x] #26 

moreover
I implemented simple IdentifyService that recognize and return any object by it's id

2018-08-02 08:08 UTC, kamil7x requested changes

2018-08-02 08:08 UTC, kamil7x commented on src/models/UserModel.js
> +      @computed get getFullName(){
It doesn't need to start with `get`. Just `fullName` will be ok

2018-08-02 08:08 UTC, kamil7x commented on src/modules/addDevice/addDevice.view.js
> +  @observable name = '';
You can use one observable object eg `@observable device = new DeviceModel()`, so you don't have to do magic in line 48. That's what models are for :)

2018-08-02 08:08 UTC, kamil7x commented on src/modules/addPlace/addPlace.view.js
> +import { Select } from 'antd';
Try to not mix external imports with internal imports.

For readability, external imports should be first.

2018-08-02 08:08 UTC, kamil7x commented on src/modules/addPlace/addPlace.view.js
> +      this.errorMsg = 'New place added';
Wow, that's not an error :D maybe we can use better name?

2018-08-02 08:08 UTC, kamil7x commented on src/modules/addPlace/addPlace.view.js
> +      this.errorMsg = 'New place added';
Or even better, if place is added successfully, redirect user to places list, or this place details view

2018-08-02 08:08 UTC, kamil7x commented on src/routers/devices.router.js
> +    {/* <Route path="/devices/add_device" render={() => <div>devices add device</div>} /> */}
You can remove commented code

2018-08-02 08:08 UTC, kamil7x commented on src/services/DeviceService.js
> +    client.delete(`/api/devices/${deviceId}`)
Nice! That's what template strings are for! :)

2018-08-02 08:08 UTC, kamil7x commented on src/stores/UsersStore.js
> +  @computed get getFullName() {
You can remove this and use `UserStore.currentUser.fullName`. If you still want to have this in store, you can `return this.currentUser.fullName` instead

2018-08-02 09:52 UTC, kamil7x requested changes

2018-08-02 09:52 UTC, kamil7x commented on src/modules/addPlace/addPlace.view.js
> +            {this.notificationMsg && <NoticeBar mode='closable' onClick={this.resetErrMessage}>{this.notificationMsg}</NoticeBar>}
You forgot to change onClick function

2018-08-03 08:01 UTC, kamil7x approved these changes

2018-08-03 08:02 UTC, merged